# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        cache: ~

        # Nom du filtre
        thumbnail:

            # Adjust la qualité de l'image
            quality: 85

            # Listes des differentes transformation
            filters: 

                # Création d'une vignette
                thumbnail: { size: [250, 150], mode: outbound }

        # Autre filtre...
        vignette:         
            quality: 75
            filters: 
                thumbnail: { size: [300, 200], mode: outbound }


