vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        authors:
            uri_prefix: /images/authors
            upload_destination: '%kernel.project_dir%/public/images/authors'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
